import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="py-0 px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 px-0 flex-1 flex flex-col justify-center items-center">
        <h1 className="m-0 leading-[1.15] text-[4rem] text-center">
          Welcome to <a href="https://nextjs.org" className="font-bold hover:underline text-[#0070f3]">Next.js</a> on Replit!
        </h1>

        <p className="text-center my-4 mx-0 leading-[1.5] text-[1.5rem]">
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className="flex items-center justify-center flex-wrap max-w-[800px] w-full sm:auto flex-col sm:flex-row">
          <a href="https://nextjs.org/docs" className="m-[1rem] p-[1.5rem] text-left text-inherit no-underline border-[1px] border-solid border-[#eaeaea] hover:text-[#0070f3] focus:text-[#0070f3] active:text-[#0070f3] hover:border-[#0070f3] focus:border-[#0070f3] active:border-[#0070f3]">
            <h2 className="mt-0 mr-0 mb-[1rem] ml-0 text-[1.5rem]">Documentation &rarr;</h2>
            <p className="m-0 text-[1.25rem] leading-[1.5]">Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="m-[1rem] p-[1.5rem] text-left text-inherit no-underline border-[1px] border-solid border-[#eaeaea] hover:text-[#0070f3] focus:text-[#0070f3] active:text-[#0070f3] hover:border-[#0070f3] focus:border-[#0070f3] active:border-[#0070f3]">
            <h2 className="mt-0 mr-0 mb-[1rem] ml-0 text-[1.5rem]">Learn &rarr;</h2>
            <p className="m-0 text-[1.25rem] leading-[1.5]">Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className="m-[1rem] p-[1.5rem] text-left text-inherit no-underline border-[1px] border-solid border-[#eaeaea] hover:text-[#0070f3] focus:text-[#0070f3] active:text-[#0070f3] hover:border-[#0070f3] focus:border-[#0070f3] active:border-[#0070f3]"
          >
            <h2 className="mt-0 mr-0 mb-[1rem] ml-0 text-[1.5rem]">Examples &rarr;</h2>
            <p className="m-0 text-[1.25rem] leading-[1.5]">Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://docs.replit.com/category/hosting"
            className="m-[1rem] p-[1.5rem] text-left text-inherit no-underline border-[1px] border-solid border-[#eaeaea] hover:text-[#0070f3] focus:text-[#0070f3] active:text-[#0070f3] hover:border-[#0070f3] focus:border-[#0070f3] active:border-[#0070f3]"
          >
            <h2 className="mt-0 mr-0 mb-[1rem] ml-0 text-[1.5rem]">Deploy &rarr;</h2>
            <p className="m-0 text-[1.25rem] leading-[1.5]">
              This website automatically deployed on Replit by hitting the run button!
            </p>
          </a>
        </div>
      </main>

      <footer className="flex flex-1 py-4 px-0 border-t-[1px] border-solid border-[#eaeaea] justify-center items-center">
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center grow"
        >
          Built on
          <span className="h-[1em] ml-[0.2rem]">
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
          Replit
        </a>
      </footer>
    </div>
  )
}

export default Home